### Importación de datos

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

### ✅ Definir una función de exploración inicial por tienda

In [3]:
def explorar_tienda(df, nombre_tienda = "Tienda"):
    print(f"\n--- {nombre_tienda}")
    
    print("Primeras filas:")
    display(df.head())
    
    print("\nInfo General:")
    print(df.info())
    
    print("\nValores nulos:")
    print(df.isnull().sum())
    
    print("\nEstadístiscas descriptivas")
    display(df.describe())
    
    print("\n Columnas únicas relevantes:")
    print("Categorías:", df['Categoría del Producto'].unique())
    print("Métodos de pago", df['Método de pago'].unique())
    print("Rango de fechas", df['Fecha de Compra'].min(), "->", df['Fecha de Compra'].max())

### Ejecutar la funcion en todas las tiendas

In [4]:
explorar_tienda(tienda, "Tienda 1")
explorar_tienda(tienda2, "Tienda 2")
explorar_tienda(tienda3, "Tienda 3")
explorar_tienda(tienda4, "Tienda 4")

--- Tienda 1
Primeras filas:

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Asistente virtual,Electrónicos,164300.0,6900.0,16/01/2021,Pedro Gomez,Bogotá,4,Tarjeta de crédito,8,4.60971,-74.08175
1,Mesa de comedor,Muebles,192300.0,8400.0,18/05/2022,Beatriz Morales,Medellín,1,Tarjeta de crédito,4,6.25184,-75.56359
2,Juego de mesa,Juguetes,209600.0,15900.0,15/03/2021,Juan Fernandez,Cartagena,1,Tarjeta de crédito,1,10.39972,-75.51444
3,Microondas,Electrodomésticos,757500.0,41000.0,03/05/2022,Juan Fernandez,Cali,4,Nequi,1,3.43722,-76.52250
4,Silla de oficina,Muebles,335200.0,20200.0,07/11/2020,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359

Info General:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2359 non-null   object
 1   Categoría del Producto  2359 non-null   object
 2   Precio                  2359 non-null   float64
 3   Costo de envío          2359 non-null   float64
 4   Fecha de Compra         2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Lugar de Compra         2359 non-null   object
 7   Calificación            2359 non-null   int64
 8   Método de pago          2359 non-null   object
 9   Cantidad de cuotas      2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB
None

Valores nulos:
Producto                  0
Categoría del Producto    0
Precio                    0
Costo de envío            0
Fecha de Compra           0
Vendedor                  0
Lugar de Compra           0
Calificación              0
Método de pago            0
Cantidad de cuotas        0
lat                       0
lon                       0
dtype: int64

Estadístiscas descriptivas

,Precio,Costo de envío,Calificación,Cantidad de cuotas,lat,lon
count,2.359000e+03,2359.000000,2359.000000,2359.000000,2359.000000,2359.000000
mean,4.878679e+05,26018.609580,3.976685,2.943196,5.365283,-74.789417
std,6.146868e+05,32860.001783,1.415370,2.819897,2.287445,1.217827
min,7.600000e+03,0.000000,1.000000,1.000000,-4.215280,-77.281110
25%,5.575000e+04,3100.000000,3.000000,1.000000,4.609710,-75.563590
50%,2.353000e+05,12400.000000,5.000000,1.000000,4.609710,-74.199040
75%,6.781000e+05,36000.000000,5.000000,4.000000,6.251840,-74.081750
max,2.977000e+06,160800.000000,5.000000,24.000000,11.544440,-67.923900

 Columnas únicas relevantes:
Categorías: ['Electrónicos' 'Muebles' 'Juguetes' 'Electrodomésticos'
 'Artículos para el hogar' 'Deportes y diversión' 'Libros'
 'Instrumentos musicales']
Métodos de pago ['Tarjeta de crédito' 'Nequi' 'Cupón' 'Tarjeta de débito']
Rango de fechas 01/01/2020 -> 31/12/2022

--- Tienda 2
Primeras filas:

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Silla de oficina,Muebles,283600.0,15300.0,04/08/2021,Izabela de León,Medellín,1,Nequi,1,6.25184,-75.56359
1,Pandereta,Instrumentos musicales,76800.0,2300.0,26/11/2020,Blanca Ramirez,Medellín,3,Tarjeta de crédito,4,6.25184,-75.56359
2,Cama king,Muebles,443300.0,23800.0,22/10/2021,Izabela de León,Pereira,5,Tarjeta de crédito,10,4.81333,-75.69611
3,Cama king,Muebles,906200.0,46400.0,04/05/2022,Maria Alfonso,Cali,5,Tarjeta de crédito,10,3.43722,-76.52250
4,Silla de oficina,Muebles,397800.0,19400.0,26/02/2022,Lucas Olivera,Bogotá,4,Tarjeta de crédito,3,4.60971,-74.08175

Info General:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2359 non-null   object
 1   Categoría del Producto  2359 non-null   object
 2   Precio                  2359 non-null   float64
 3   Costo de envío          2359 non-null   float64
 4   Fecha de Compra         2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Lugar de Compra         2359 non-null   object
 7   Calificación            2359 non-null   int64
 8   Método de pago          2359 non-null   object
 9   Cantidad de cuotas      2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB
None

Valores nulos:
Producto                  0
Categoría del Producto    0
Precio                    0
Costo de envío            0
Fecha de Compra           0
Vendedor                  0
Lugar de Compra           0
Calificación              0
Método de pago            0
Cantidad de cuotas        0
lat                       0
lon                       0
dtype: int64

Estadístiscas descriptivas

,Precio,Costo de envío,Calificación,Cantidad de cuotas,lat,lon
count,2.359000e+03,2359.000000,2359.000000,2359.000000,2359.000000,2359.000000
mean,4.732274e+05,25216.235693,4.037304,2.902501,5.499753,-74.742963
std,5.955595e+05,31741.375166,1.356153,2.848416,2.351118,1.185997
min,7.600000e+03,0.000000,1.000000,1.000000,-4.215280,-77.281110
25%,5.455000e+04,2900.000000,4.000000,1.000000,4.609710,-75.563590
50%,2.182000e+05,11600.000000,5.000000,1.000000,4.609710,-74.199040
75%,6.777000e+05,35450.000000,5.000000,4.000000,6.251840,-74.081750
max,2.953400e+06,162500.000000,5.000000,24.000000,11.544440,-67.923900

 Columnas únicas relevantes:
Categorías: ['Muebles' 'Instrumentos musicales' 'Deportes y diversión' 'Electrónicos'
 'Artículos para el hogar' 'Juguetes' 'Electrodomésticos' 'Libros']
Métodos de pago ['Nequi' 'Tarjeta de crédito' 'Cupón' 'Tarjeta de débito']
Rango de fechas 01/01/2020 -> 31/12/2022

--- Tienda 3
Primeras filas:

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Secadora de ropa,Electrodomésticos,1285100.0,66600.0,17/12/2021,Camila Rivera,Santa Marta,4,Tarjeta de crédito,4,11.24079,-74.19904
1,Mesa de noche,Muebles,290100.0,13600.0,10/02/2021,Maria Alfonso,Cali,3,Tarjeta de crédito,1,3.43722,-76.52250
2,Guitarra acústica,Instrumentos musicales,303500.0,17400.0,22/01/2023,Lucas Olivera,Bogotá,5,Tarjeta de crédito,3,4.60971,-74.08175
3,Balón de voleibol,Deportes y diversión,58800.0,3300.0,22/03/2022,Pedro Gomez,Barranquilla,4,Tarjeta de crédito,6,10.96854,-74.78132
4,Armario,Muebles,521100.0,25900.0,12/01/2022,Blanca Ramirez,Bogotá,1,Tarjeta de crédito,1,4.60971,-74.08175

Info General:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2359 entries, 0 to 2358
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2359 non-null   object
 1   Categoría del Producto  2359 non-null   object
 2   Precio                  2359 non-null   float64
 3   Costo de envío          2359 non-null   float64
 4   Fecha de Compra         2359 non-null   object
 5   Vendedor                2359 non-null   object
 6   Lugar de Compra         2359 non-null   object
 7   Calificación            2359 non-null   int64
 8   Método de pago          2359 non-null   object
 9   Cantidad de cuotas      2359 non-null   int64
 10  lat                     2359 non-null   float64
 11  lon                     2359 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.3+ KB
None

Valores nulos:
Producto                  0
Categoría del Producto    0
Precio                    0
Costo de envío            0
Fecha de Compra           0
Vendedor                  0
Lugar de Compra           0
Calificación              0
Método de pago            0
Cantidad de cuotas        0
lat                       0
lon                       0
dtype: int64

Estadístiscas descriptivas

,Precio,Costo de envío,Calificación,Cantidad de cuotas,lat,lon
count,2.359000e+03,2359.000000,2359.000000,2359.000000,2359.000000,2359.000000
mean,4.654598e+05,24805.680373,4.048326,2.967783,5.437076,-74.733463
std,5.806434e+05,30945.889626,1.386426,2.812153,2.405272,1.224572
min,7.600000e+03,0.000000,1.000000,1.000000,-4.215280,-77.281110
25%,5.740000e+04,3100.000000,4.000000,1.000000,4.609710,-75.563590
50%,2.263000e+05,11900.000000,5.000000,2.000000,4.609710,-74.199040
75%,6.660500e+05,34950.000000,5.000000,4.000000,6.251840,-74.081750
max,2.968200e+06,158400.000000,5.000000,24.000000,11.544440,-67.923900

 Columnas únicas relevantes:
Categorías: ['Electrodomésticos' 'Muebles' 'Instrumentos musicales'
 'Deportes y diversión' 'Electrónicos' 'Juguetes'
 'Artículos para el hogar' 'Libros']
Métodos de pago ['Tarjeta de crédito' 'Nequi' 'Cupón' 'Tarjeta de débito']
Rango de fechas 01/01/2020 -> 31/12/2021

--- Tienda 4
Primeras filas:

,Producto,Categoría del Producto,Precio,Costo de envío,Fecha de Compra,Vendedor,Lugar de Compra,Calificación,Método de pago,Cantidad de cuotas,lat,lon
0,Lavavajillas,Electrodomésticos,1084800.0,56000.0,11/11/2022,Rafael Acosta,Bogotá,4,Tarjeta de crédito,3,4.60971,-74.08175
1,Cama box,Muebles,473800.0,25400.0,03/01/2020,Izabela de León,Cúcuta,5,Tarjeta de crédito,2,7.89391,-72.50782
2,Balón de baloncesto,Deportes y diversión,23700.0,0.0,25/12/2022,Maria Alfonso,Medellín,5,Nequi,1,6.25184,-75.56359
3,Modelado predictivo,Libros,57700.0,1300.0,23/11/2021,Lucas Olivera,Medellín,3,Nequi,1,6.25184,-75.56359
4,Auriculares,Electrónicos,138900.0,5600.0,25/04/2022,Blanca Ramirez,Bogotá,4,Tarjeta de crédito,7,4.60971,-74.08175

Info General:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2358 entries, 0 to 2357
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Producto                2358 non-null   object
 1   Categoría del Producto  2358 non-null   object
 2   Precio                  2358 non-null   float64
 3   Costo de envío          2358 non-null   float64
 4   Fecha de Compra         2358 non-null   object
 5   Vendedor                2358 non-null   object
 6   Lugar de Compra         2358 non-null   object
 7   Calificación            2358 non-null   int64
 8   Método de pago          2358 non-null   object
 9   Cantidad de cuotas      2358 non-null   int64
 10  lat                     2358 non-null   float64
 11  lon                     2358 non-null   float64
dtypes: float64(4), int64(2), object(6)
memory usage: 221.2+ KB
None

Valores nulos:
Producto                  0
Categoría del Producto    0
Precio                    0
Costo de envío            0
Fecha de Compra           0
Vendedor                  0
Lugar de Compra           0
Calificación              0
Método de pago            0
Cantidad de cuotas        0
lat                       0
lon                       0
dtype: int64

Estadístiscas descriptivas

,Precio,Costo de envío,Calificación,Cantidad de cuotas,lat,lon
count,2.358000e+03,2358.000000,2358.000000,2358.000000,2358.000000,2358.000000
mean,4.403629e+05,23459.457167,3.995759,2.896098,5.413519,-74.774597
std,5.687556e+05,30279.100836,1.403063,2.730393,2.376728,1.199749
min,7.600000e+03,0.000000,1.000000,1.000000,-4.215280,-77.281110
25%,5.340000e+04,2900.000000,3.000000,1.000000,4.609710,-75.563590
50%,2.094500e+05,10950.000000,5.000000,1.000000,4.609710,-74.199040
75%,6.342250e+05,33300.000000,5.000000,4.000000,6.251840,-74.081750
max,2.902200e+06,154700.000000,5.000000,18.000000,11.544440,-67.923900

 Columnas únicas relevantes:
Categorías: ['Electrodomésticos' 'Muebles' 'Deportes y diversión' 'Libros'
 'Electrónicos' 'Instrumentos musicales' 'Juguetes'
 'Artículos para el hogar']
Métodos de pago ['Tarjeta de crédito' 'Nequi' 'Cupón' 'Tarjeta de débito']
Rango de fechas 01/01/2020 -> 31/12/2022

### ✅ 2. Definir una función para limpieza básica para cada tienda

* convertir fecha en formato datetime para todas las tiendas

In [5]:
for df in [tienda,tienda2,tienda3, tienda4]:
    df['Fecha de Compra'] = pd.to_datetime(df['Fecha de Compra'], dayfirst= True)

# 1. Análisis de facturación

In [94]:
# Definir una función para calcular la facturación total de cada tienda

def ingreso_total_por_tienda(df, nombre_tienda = "Tienda"):
    ingreso = df['Precio'].sum()
    return nombre_tienda, ingreso

In [97]:
# Convertir a un dataframe los ingresos de cada tienda
datos_ingresos = [
    ingreso_total_por_tienda(tienda, "Tienda 1"),
    ingreso_total_por_tienda(tienda2, "Tienda 2"),
    ingreso_total_por_tienda(tienda3, "Tienda 3"),
    ingreso_total_por_tienda(tienda4, "Tienda 4")
]

df_facturacion = pd.DataFrame(datos_ingresos, columns=["Tienda", "Ingreso Total"])
# Convertir los ingresos a millones para que sea más legible visualmente
df_facturacion['Ingreso Total(en Millones)'] = (df_facturacion['Ingreso Total'] / 1e6).map(lambda x: f"$ {x:,.2f}")
display(df_facturacion)

     Tienda  Ingreso Total Ingreso Total(en Millones)
0  Tienda 1   1.150880e+09                 $ 1,150.88
1  Tienda 2   1.116344e+09                 $ 1,116.34
2  Tienda 3   1.098020e+09                 $ 1,098.02
3  Tienda 4   1.038376e+09                 $ 1,038.38

# 2. Ventas por categoría

In [101]:
# Definir una función para calcular las ventas por categoría

def ventas_por_categoria(df, nombre_tienda):
    ventas = df['Categoría del Producto'].value_counts().reset_index()
    ventas.columns = ['Categoría del Producto', 'Cantidad Vendida']
    ventas["Tienda"] = nombre_tienda
    return ventas

In [102]:
# Crear lista de DataFrames con la tienda incluida
lista_df_ventas_categoria = [

    ventas_por_categoria(tienda, "Tienda 1"),
    ventas_por_categoria(tienda2, "Tienda 2"),
    ventas_por_categoria(tienda3, "Tienda 3"),
    ventas_por_categoria(tienda4, "Tienda 4")
]

df_ventas_categoria = pd.concat(lista_df_ventas_categoria, ignore_index= True)
display(df_ventas_categoria)

     Categoría del Producto  Cantidad Vendida    Tienda
0                   Muebles               465  Tienda 1
1              Electrónicos               448  Tienda 1
2                  Juguetes               324  Tienda 1
3         Electrodomésticos               312  Tienda 1
4      Deportes y diversión               284  Tienda 1
5    Instrumentos musicales               182  Tienda 1
6                    Libros               173  Tienda 1
7   Artículos para el hogar               171  Tienda 1
8                   Muebles               442  Tienda 2
9              Electrónicos               422  Tienda 2
10                 Juguetes               313  Tienda 2
11        Electrodomésticos               305  Tienda 2
12     Deportes y diversión               275  Tienda 2
13   Instrumentos musicales               224  Tienda 2
14                   Libros               197  Tienda 2
15  Artículos para el hogar               181  Tienda 2
16                  Muebles               499  Tienda 3
17             Electrónicos               451  Tienda 3
18                 Juguetes               315  Tienda 3
19        Electrodomésticos               278  Tienda 3
20     Deportes y diversión               277  Tienda 3
21                   Libros               185  Tienda 3
22   Instrumentos musicales               177  Tienda 3
23  Artículos para el hogar               177  Tienda 3
24                  Muebles               480  Tienda 4
25             Electrónicos               451  Tienda 4
26                 Juguetes               338  Tienda 4
27     Deportes y diversión               277  Tienda 4
28        Electrodomésticos               254  Tienda 4
29  Artículos para el hogar               201  Tienda 4
30                   Libros               187  Tienda 4
31   Instrumentos musicales               170  Tienda 4

# 3. Calificación promedio de la tienda

# 4. Productos más y menos vendidos

# 5. Envío promedio por tienda